In order to successfully complete this assignment, you must follow all the instructions in this notebook and upload your edited ipynb file to [D2L](http://d2l.msu.edu/) with your answers on or before **10:00am on Friday, October 29th**.

In [1]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

In [2]:
# import for checking answers
from answercheck import checkanswer

# 1. Change of bases (30 pts)

We call the basis formed by the vectors:
$$
\vec{e}_1=\left(\begin{array}{r}
1\\
0\\
0
\end{array}
\right),\,\,\,\,\,
\vec{e}_2=\left(\begin{array}{r}
0\\
1\\
0
\end{array}
\right),\,\,\,\,\,
\vec{e}_3=\left(\begin{array}{r}
0\\
0\\
1
\end{array}
\right)
$$
the _standard basis_.


Consider three column vectors:
$$
\vec{b}_1=\left(\begin{array}{r}
-2\\
2\\
-1
\end{array}
\right),\,\,\,\,\,
\vec{b}_2=\left(\begin{array}{r}
-7\\
8\\
-4
\end{array}
\right),\,\,\,\,\,
\vec{b}_3=\left(\begin{array}{r}
8\\
-9\\
5
\end{array}
\right).
$$

&#9989;  **<font color=red>QUESTION 1.1:</font>** (3 pts)
Form a $3\times3$ (numpy) matrix $B$ whose columns are the vectors $\vec{b}_1$, $\vec{b}_2$ and $\vec{b}_3$.

In [4]:
# Put your answer to the above question here
B = np.matrix([[-2,2,-1],[-7,8,-4],[8,-9,5]]).T
sym.Matrix(B)

⎡-2  -7  8 ⎤
⎢          ⎥
⎢2   8   -9⎥
⎢          ⎥
⎣-1  -4  5 ⎦

In [5]:
checkanswer.matrix( B, '69807acb597f64933aca90e886436745' );


    Trying to convert to float using ```A = A.astype(float)```.

Testing [[-2. -7.  8.]
 [ 2.  8. -9.]
 [-1. -4.  5.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.2:</font>** (5 pts)
Check that vectors are linearly independent, i.e. they can form a basis.

In [6]:
# Put your answer to the above question here
print(np.linalg.matrix_rank(B))

3


As the rank of matrix is $3$ and it is of a $3\times3$, this means that all the rows and columns are linearly independent. Therefore, this means that the vectors are linearly independent.

&#9989;  **<font color=red>QUESTION 1.3:</font>** (5 pts)
Consider the standard basis and the basis formed by $\vec{b}_1$, $\vec{b}_2$ and $\vec{b}_3$. Describe how the matrix $B$ relates the two.

The matrix $B$ is used to transform the coordinates in this basis to the standard basis.The matrix $B$ is the basis formed by $\vec{b}_1$, $\vec{b}_2$ and $\vec{b}_3$, and the inverse of the basis mltiplied by a point in the standard basis will result in points coordinate.

&#9989;  **<font color=red>QUESTION 1.4:</font>** (5 pts)
Consider a point whose coordinates in the standard basis are $(1,1,1)$. Calculate its coordinates in the basis of $\vec{b}_1$, $\vec{b}_2$ and $\vec{b}_3$. Store the result in variable `rprime`.

In [7]:
# Put your answer to the above question here
u = np.matrix([[1,1,1]]).T
inv = np.linalg.inv(B)
rprime = inv*u
sym.Matrix(rprime)

⎡-6.0⎤
⎢    ⎥
⎢5.0 ⎥
⎢    ⎥
⎣3.0 ⎦

In [8]:
checkanswer.matrix( rprime, 'b6cfe5b9898e5b73355743a069ed34d4' );

Testing [[-6.]
 [ 5.]
 [ 3.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.5:</font>** (5 pts)
Consider a point whose coordinates in the $(\vec{b}_1, \vec{b}_2, \vec{b}_3)$ basis are $(1,1,1)$. Calculate its coordinates in the standard basis. Store the result in variable `rprime`.

In [10]:
u = np.matrix([[1,1,1]]).T
rprime = B*u

In [11]:
checkanswer.matrix( rprime, 'ed83de1f7a4aef6e43f0783e4d435415' );


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[-1.]
 [ 1.]
 [ 0.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.6:</font>** (7 pts)
Let us interpret matrix $B$ as a linear transformation. Explain how the transformation changes a three-dimensional cube occuping the region $[0,1]\times[0,1]\times[0,1]$. How does the volume of the cube change under this transformation? Provide a numerical answer based on the properties of $B$.

The value of the determinant tells us the scaling happening to the cube. In our matrix $B$ over here, the value of determinant is $-1$. As the determinant is negative, then it implies that the there is a reflection. $-1$ will not change the volume of the cube because it has been just stresses and sheared, but the orientation of the cube would be changed. The sides will still remain parallel.

In [12]:
# Put your calculation here
print(np.linalg.det(B))

-1.0


# 2. Matrix representation of vector spaces (25 pts)

Consider the matrix
$$
A=\left(\begin{array}{rrr}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}
\right)
$$

&#9989;  **<font color=red>QUESTION 2.1:</font>** (5 pts)
Find the row space of $A$, by providing a basis for it.

In [13]:
# Put your answer to the above question here
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
rref = sym.Matrix(A).rref()[0]
rref

⎡1  0  -1⎤
⎢        ⎥
⎢0  1  2 ⎥
⎢        ⎥
⎣0  0  0 ⎦

The row space of $A$ will be:
$$row(A) = \{r(1,0,-1)^\top+s(0,1,2)^\top : r,s \in \mathbb{R} \} = \mbox{span}((1,0,-1)^\top,(0,1,2)^\top)$$

&#9989;  **<font color=red>QUESTION 2.2:</font>** (5 pts)
Find the null space of $A$ by providing a basis for it.

In [14]:
sym.Matrix(A).nullspace()

⎡⎡1 ⎤⎤
⎢⎢  ⎥⎥
⎢⎢-2⎥⎥
⎢⎢  ⎥⎥
⎣⎣1 ⎦⎦

Therefore, the null space would of $A$ would be:
$$
{z}\times{\left[\begin{matrix}
1\\
-2\\
1
\end{matrix}
\right]}
$$

&#9989;  **<font color=red>QUESTION 2.3:</font>** (5 pts)
Find the column space of $A$ by providing a basis for it.

In [15]:
# Put your answer to the above question here
At = np.matrix(A).T
rref_inv = sym.Matrix(At).rref()[0]
rref_inv

⎡1  0  -1⎤
⎢        ⎥
⎢0  1  2 ⎥
⎢        ⎥
⎣0  0  0 ⎦

Therefore, the column space of $A$ would be:
$$col(A) = \{a(1,0,-1)^\top+b(0,1,2)^\top : a,b \in \mathbb{R} \} = \mbox{span}((1,0,-1)^\top,(0,1,2)^\top)$$

&#9989;  **<font color=red>QUESTION 2.4:</font>** (5 pts)
Find the null space of $A^T$ by providing a basis for it.

In [16]:
sym.Matrix(At).nullspace()

⎡⎡1 ⎤⎤
⎢⎢  ⎥⎥
⎢⎢-2⎥⎥
⎢⎢  ⎥⎥
⎣⎣1 ⎦⎦

Therefore, the null space would of $A^T$ would be:
$$
{z}\times{\left[\begin{matrix}
1\\
-2\\
1
\end{matrix}
\right]}
$$

&#9989;  **<font color=red>QUESTION 2.5:</font>** (5 pts)
Calculate the rank of $A$. How are the rank, dimension of the null space and the size of $A$ related?

In [17]:
rank = np.linalg.matrix_rank(A)
print(rank)

2


**If the rank is decreased, then the dimension of the null space increases, but the sum of the rank and the dimension of the null space would always be equal to the size of $A$**

# 3. Eigenproblems: Fibonacci-like sequence (45 pts)


Consider the following sequence of numbers, called Fibonacci sequence, $f_n$, $n=0,1,2,\dots$:
$$
f_0=0,\,\,\,\,\,f_1=1,
$$
$$
f_n=f_{n-1}+f_{n-2}\,\mbox{for $n\geq2$}.
$$
In other words, the first two numbers are initialized to be $0$ and $1$ and each next number in the sequnce is given as a sum of the previous two. Using the recursive formula it is easy to see that $f_2=1$, $f_3=2$, $f_4=3$, $f_5=5$, $f_6=8$, etc.

A drawback of the recursive formula is that if we would like to calculate, say, one millionth number in the sequence (i.e. $n=1000000$) we need to do one million additions to get to that $n$.
It is desirable to derive a closed form expression that would allow us immediately evaluate the $n$-th number $f_n$ as function of $n$ without relying on the recursive formula.

At first sight, this problem has nothing to do with linear algebra. However, the problem of deriving the direct formula can be reformulated as an eigenproblem!

Here we briefly discuss the steps for the Fibonacci sequence where the result is known and then apply them to another sequence given below. Since producing the next number in the sequence requires two previous numbers, let us
consider a two-dimensional vector $\vec{v}_k$ that packs together $k$-th and $(k+1)$-th numbers:
$$
\vec{v}_k=\left(\begin{array}{l}
f_{k+1}\\
f_k
\end{array}
\right)
$$
Then
$$
\vec{v}_{k-1}=\left(\begin{array}{l}
f_{k}\\
f_{k-1}
\end{array}
\right)
$$
and we can relate $\vec{v}_{k}$ and $\vec{v}_{k-1}$ by an action of a $2\times2$ matrix $T$. Namely, using the recursive formula:
$$
\vec{v}_k=
\left(\begin{array}{l}
f_{k+1}\\
f_k
\end{array}
\right)=
\left(\begin{array}{l}
f_{k}+f_{k-1}\\
f_k
\end{array}
\right)=
\left(\begin{array}{l}
1\cdot f_{k}+1\cdot f_{k-1}\\
1\cdot f_k + 0\cdot f_{k-1}
\end{array}
\right)=
\left(\begin{array}{ll}
1 & 1 \\
1 & 0
\end{array}
\right)
\left(\begin{array}{l}
f_{k}\\
f_{k-1}
\end{array}
\right)\equiv
T\vec{v}_{k-1}
$$
where the transformation matrix $T$ by this construction is
$$
T\equiv \left(\begin{array}{ll}
1 & 1 \\
1 & 0
\end{array}
\right).
$$
The $n$-th number in the sequence is given as the top component of the vector $\vec{v}_{n-1}$ which can be evaluated as a repetitive application of the matrix $T$ on the initial vector $\vec{v}_0$:
$$
\vec{v}_{n-1}=T\vec{v}_{n-2}=T^2\vec{v}_{n-3}=\dots=T^{n-1}\vec{v}_0.
$$
For the Fibonacci sequence the initial vector is
$$
\left(\begin{array}{l}
s_1\\
s_0
\end{array}
\right),
$$
with the starting values $s_1=1$ and $s_0=0$. (If we keep $s_0$ and $s_1$ as variables in the code, rather than directly coding 0 and 1, it gives us flexibility to explore different sequences by simply changing these two parameters.)

The next step is to solve the eigenproblem for $T$, i.e. find its eigenvalues $\lambda_1$, $\lambda_2$ and corresponding eigenvectors $\vec{e}_1$ and $\vec{e}_2$. Assume this has been done. Then we can expand the initial vector $\vec{v}_0$ in the basis of the eigenvectors $\vec{e}_1$ and $\vec{e}_2$, which means finding the coefficients $c_1$ and $c_2$ such that
$$
\vec{v}_0=c_1\vec{e_1}+c_2\vec{e_2}.
$$

Why is this helpful? While the action of $T^{n-1}$ on $\vec{v}_0$ is complicated, the action of $T$ on its eigenvector simply produces the same vector multiplied by the corresponding eigenvalue. Thus,
$$
T^{n-1}\vec{v}_0=c_1T^{n-1}\vec{e_1}+c_2T^{n-1}\vec{e_2}=c_1\lambda_1^{n-1}\vec{e_1}+c_2\lambda_2^{n-1}\vec{e_2}.
$$
Once we solved the eigenproblem for the transformation matrix $T$, the closed form expression for the vector $\vec{v}_{n-1}$ whose first component is the $n$-th Fibonacci number, is given in terms of the eigenvalues and eigenvectors of $T$:
$$
\vec{v}_{n-1}=c_1\lambda_1^{n-1}\vec{e_1}+c_2\lambda_2^{n-1}\vec{e_2},
$$
where $c_1$ and $c_2$ are the "coordinates" of the initial vector $\vec{v}_0$ in the basis of the eigenvectors of $T$.



#### Now consider a new sequence.

Consider the following iterative formula:
$$
f_n=f_{n-1}+2f_{n-2}-2f_{n-3}
$$
To start the sequence we need to set
$$
f_0=s_0,\,\,\,\,\,
f_1=s_1,\,\,\,\,\,
f_2=s_2
$$
where we leave $s_0$, $s_1$ and $s_2$ as free parameters that we can change in the code. To start, we can set $s_0=1$, $s_1=2$, $s_2=3$.



In [18]:
# set the first three terms of the sequence here
# so they can be easily changed to produce different sequences
s0 = 1
s1 = 2
s2 = 3

print( "Starting values:" )
print( "s0 =", s0 )
print( "s1 =", s1 )
print( "s2 =", s2 )

Starting values:
s0 = 1
s1 = 2
s2 = 3


&#9989;  **<font color=red>QUESTION 3.1:</font>** (4 pts)
Calculate first ten members of the sequence with pen and paper. You will use them to test the code.


$s_0 = 1,
s_1 = 2,
s_2 = 3,
s_4 = 5,
s_5 = 7,
s_6 = 11,
s_7 = 15,
s_8 = 23,
s_9 = 31,
s_{10} = 47$

&#9989;  **<font color=red>QUESTION 3.2:</font>** (7 pts)
Write a function that employs the recursive formula and returns the $n$-th number in the sequence. To help you get started the code below provides handling of the special cases.


In [19]:
# function to produce n-th number of the following sequence:
# f0=s0, f1=s1, f2=s2 (s0, s1, s2 -- preset parameters)
# f_n = f_{n-1} + 2*f_{n-2} - 2*f_{n-3}
# Input: n
# Return: f_n
def get_n_value( n ):

    # handle special cases for the first three elements
    if n<0:
        return 0

    elif n==0:
        return s0
    
    elif n==1:
        return s1
    
    elif n==2:
        return s2

    # the general case, n>2
    else:

        # ADD YOUR CODE HERE
        # STORE THE FINAL RESULT IN fn VARIABLE
        fn = 0
        fn = get_n_value(n-1) + (2*get_n_value(n-2)) - (2*get_n_value(n-3))
        
        return fn


&#9989;  **<font color=red>QUESTION 3.3:</font>** (2 pts)
Run the code below to get the first ten elements of the sequence. Compare with the pen and paper calculation you have done above.


In [20]:
# first ten entries in the sequence
for k in range(0,10): 
    print( get_n_value(k) )


1
2
3
5
7
11
15
23
31
47


&#9989;  **<font color=red>QUESTION 3.4:</font>** (5 pts)
Since our sequence employs three previous elements in the recursive formula, we construct a three-dimensional vector:
$$
\vec{v}_k=\left(\begin{array}{l}
f_{k+2}\\
f_{k+1}\\
f_k
\end{array}
\right).
$$
Write down the $3\times3$ matrix $T$ that relates $\vec{v}_k$ and $\vec{v}_{k-1}$.


In [21]:
# Put your answer to the above question here
T = np.matrix([[1,2,-2],[1,0,0],[0,1,0]])

In [22]:
checkanswer.matrix( T, '201c7aff1a3d7cac87c551ee531f9246' );


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[ 1.  2. -2.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 3.5:</font>** (5 pts)
Use `numpy` to calculate the eigenvalues and eigenvectors of the matrix $T$. Store them in variables `eigvals` and `eigvecs`.


In [23]:
# Put your answer to the above question here
eigvals, eigvecs = np.linalg.eig(T)
print(eigvals)

[-1.41421356  1.41421356  1.        ]


In [24]:
checkanswer.matrix( eigvecs, '1a6e4e83d1dd790ce9177720442476dd' );

Testing [[ 0.75593  0.75593  0.57735]
 [-0.53452  0.53452  0.57735]
 [ 0.37796  0.37796  0.57735]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 3.6:</font>** (5 pts)
Separate the three eigenvectors into three variables `e1`, `e2`, `e3`. (`numpy` subroutines typically return a matrix whose columns are eigenvectors. Here you convert them into three three-element arrays.)


In [25]:
# Put your answer to the above question here
e1 = eigvecs[:,0]
e2 = eigvecs[:,1]
e3 = eigvecs[:,2]
print(e1)
print(e2)
print(e3)

[[ 0.75592895]
 [-0.53452248]
 [ 0.37796447]]
[[0.75592895]
 [0.53452248]
 [0.37796447]]
[[0.57735027]
 [0.57735027]
 [0.57735027]]


&#9989;  **<font color=red>QUESTION 3.7:</font>** (5 pts)
Expand the initial vector
$$
\vec{v}_0=\left(\begin{array}{l}
s_2\\
s_1\\
s_0
\end{array}
\right).
$$
in the basis of the eigenvectors $(\vec{e}_1,\vec{e}_2,\vec{e}_3)$. This problem statement is equivalent to the problem you solved while working on the change of basis. You are looking for three values $c_1$, $c_2$ and $c_3$ such that
$$
\vec{v}_0=c_1\vec{e}_1+c_2\vec{e}_2+c_3\vec{e}_3.
$$
Store the resulting coefficients in variables `c1`, `c2` and `c3`.

In [26]:
# Put your answer to the above question here
s = np.matrix([[3,2,1]]).T
x = np.linalg.solve(eigvecs,s)
c1 = x[0,0]
c2 = x[1,0]
c3 = x[2,0]
v = c1*e1 + c2*e2 + c3*e3
print(c1)

-0.16049172901586461


In [27]:
checkanswer.float( c1, '8b36ea47f7156f5f8ee1aca4d6e792c6', decimal_accuracy=4);


    Trying to convert to a float using ```A = float(A)```.

Testing -0.1605
Answer seems to be correct



In [28]:
checkanswer.float( c2, 'ea6cc08fa6c49fca7bf4db7b2167097f', decimal_accuracy=4 );


    Trying to convert to a float using ```A = float(A)```.

Testing 5.452
Answer seems to be correct



In [29]:
checkanswer.float( c3, '682023ea8a64e703f645b7425cd77ec7', decimal_accuracy=4 );


    Trying to convert to a float using ```A = float(A)```.

Testing -1.7321
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 3.8:</font>** (8 pts)
Now we have all the components to write a closed form expression for the $n$-th element of the sequence:
$$
\vec{v}_{n-2}=c_1\lambda_1^{n-2}\vec{e_1}+c_2\lambda_2^{n-2}\vec{e_2}+c_3\lambda_3^{n-2}\vec{e_3},
$$
where the first component of the vector $\vec{v}_{n-2}$ is the $n$-th element $f_n$. ($\lambda_1$, $\lambda_2$ and $\lambda_3$ denote the eigenvalues of $T$ that you found earlier.)

Write a function that incorporates the above expression and returns $f_n$.


In [30]:
# function to produce n-th number of the following sequence:
# f0=s0, f1=s1, f2=s2 (s0, s1, s2 -- preset parameters)
# f_n = f_{n-1} + 2*f_{n-2} - 2*f_{n-3}
# by using direct formula
# Input: n
# Return: f_n
def get_n_formula( n ):

    if n==0:
        return s0
    
    elif n==1:
        return s1
    
    elif n==2:
        return s2
    
    # calculation starts with n>2
    
        # ADD YOUR CODE HERE
        # STORE THE FINAL RESULT IN fn VARIABLE
    else:
        fn = 0
        fn = (c1*(eigvals[0]**(n-2))*e1) + (c2*(eigvals[1]**(n-2))*e2) + (c3*(eigvals[2]**(n-2))*e3)
    
        return int(fn[0,0])


&#9989;  **<font color=red>QUESTION 3.9:</font>** (2 pts)
Run the code below to get the first ten elements of the sequence with the direct formula. Compare with the pen and paper calculation and the function relying on the recursive formula you have written above.


In [31]:
# first ten entries in the sequence
for k in range(0,10): 
    print( get_n_formula(k) )


1
2
3
5
7
11
15
23
31
47


&#9989;  **<font color=red>QUESTION 3.10:</font>** (2 pts)
Use the function `get_n_formula()` you have written above to calculate the 1000-th element of the sequence. Store it in `x`.


In [34]:
# Put your answer to the above question here
x = get_n_formula(999)
print(x)
x_str = str(x)
print(len(x_str))

4910085911848927080985565851533501642542924666474414902090354997083186440038897458747608637419549910881259496677567212228964127248904995006155986042880
151


Because the 1000-th element would be 999 becuase the series starts from 0.