In order to successfully complete this assignment, you must follow all the instructions in this notebook and upload your edited ipynb file to [D2L](http://d2l.msu.edu/) with your answers on or before **10:00am on Friday November 12th**.

**BIG HINT:** Read the entire homework before starting. 

# Homework 4: Projection and diagonalization

In [1]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

In [2]:
# import for checking answers
from answercheck import checkanswer

# 1. Solving ODE system (35 pts)

Consider the linear ODE system 
$$\begin{aligned}
\dot{x}_1 &= 3x_1-x_2\\
\dot{x}_2 &= -2x_1+3x_2+2x_3\\
\dot{x}_3 &= 4x_1-x_2-2x_3\\
\end{aligned}$$


with initial values
$$\begin{aligned}
x_1(0) &= 1\\
x_2(0) &= -4\\
x_3(0) &= 0\\
\end{aligned}$$

We want to find the solution $(x_1(t),x_2(t),x_3(t))$ at a later time $t>0$ following the steps below.

&#9989;  **<font color=red>QUESTION 1.1:</font>** (5 pts)
Rewrite this ODE system as a matrix form $$\dot{x} = Ax$$

In [3]:
# Put your answer to the above question here
A = np.matrix([[3,-1,0],[-2,3,2],[4,-1,-2]])

In [4]:
from answercheck import checkanswer

checkanswer.matrix(A,"f7f629309b0e5b510b901d575750d406");


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[ 3. -1.  0.]
 [-2.  3.  2.]
 [ 4. -1. -2.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.2:</font>** (5 pts)
Find an invertible matrix $C$ such that $C^{-1}AC$ is a diagonal matrix. (hint: call ```np.linalg.eig```).

In [5]:
# Put your answer to the above question here
C = np.linalg.eig(A)[1]


In [6]:
from answercheck import checkanswer
checkanswer.matrix(C,"1307c7cead6d3a31bc1e90b89cb3e5ef");

Testing [[ 0.08215  0.70153  0.69782]
 [ 0.40397 -0.41933  0.47483]
 [-0.91107  0.57621  0.53627]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.3:</font>** (5 pts)
For the matrix $C$ from the previous part, by introducing the vector $$y=[y_1,y_2,y_3]^\top=C^{-1}x,$$ the original ODE system could be rewritten as $\dot{y}=Jy$. Define such a matrix $J$.

In [7]:
#Put your answer here
eigval, eigvec = np.linalg.eig(A)
J = np.matrix([[eigval[0],0,0],[0,eigval[1],0],[0,0,eigval[2]]])
print(eigval)

[-1.91728599  3.59773519  2.3195508 ]


In [8]:
from answercheck import checkanswer
checkanswer.matrix(J,"4e5640c14a84602e121f0f1fbd63e8c7");


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[-1.91729  0.       0.     ]
 [ 0.       3.59774  0.     ]
 [ 0.       0.       2.31955]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.4:</font>** (5 pts) Convert the matrix form $\dot{y}=Jy$ back to 3 equations of $y_1(t),y_2(t),y_3(t)$. What's special about these equations?

$$\dot{y}_1(t)= -1.91728599y_1$$
$$\dot{y}_2(t)=  3.59773519y_2$$
$$\dot{y}_3(t)=  2.3195508y_3$$

The special thing about these equations is that they first order linear homogeneous equations. The equations are seperable. All the equations are distinct and they are not mixed. The equations are decomposible.

&#9989;  **<font color=red>QUESTION 1.5:</font>** (5 pts) Let $a \in \mathbb{R}$ be a scalar, recall that a 1-dimensional ODE 
$$ \dot{z} = az
$$
has the closed-form solution 
$$
z(t) = z(0)e^{at}
$$


Feel free to insert this solution back to the ODE to verify that it is indeed a solution.

Use this idea to write out the closed-form solution of the ODEs you derived in QUESTION 1.4 .

$$y_1(t) = y_1(0)e^{-1.91728599t}$$
$$y_2(t) = y_2(0)e^{3.59773519t}$$
$$y_3(t) = y_3(0)e^{2.3195508t}$$

&#9989;  **<font color=red>QUESTION 1.6:</font>** (5 pts) At the beginning of this part, the initial values $(x_1(0),x_2(0),x_3(0))$ are provided. Use them to find the initial values of  $(y_1(0),y_2(0),y_3(0))$. Store your answer as a $3\times 1$ vector called `y0`.


In [9]:
# Put your answer to the above question here
C_inv = np.linalg.inv(C)
x0 = np.matrix([[1,-4,0]]).T
y0 = C_inv*x0

In [10]:
from answercheck import checkanswer
checkanswer.vector(y0,"c7c78c0981c4c62a19149e39b9641d55");


    Trying to convert to a column vector using ```A = A.T```.

Testing [[ 1.00234  5.6088  -4.32361]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.7:</font>** (5 pts) Use `y0` and the closed-form solutions of $y(t)$ you derived in QUESTION 1.5  to compute $y(1)$ and store your answer as a $3\times 1$ vector `y1`.

In [11]:
#Put your answer here
y1=np.matrix([[y0[0,0]*np.exp(eigval[0])], [y0[1,0]*np.exp(eigval[1])], [y0[2,0]*np.exp(eigval[2])]])

In [12]:
from answercheck import checkanswer
checkanswer.vector(y1,"e268e5af96ec6db7e24e6c0c4674bb7d");


    Trying to convert to a column vector using ```A = A.T```.

Testing [[ 1.4735000e-01  2.0480778e+02 -4.3975910e+01]]
Answer seems to be correct



# 2. Projection (35 pts)

Given a vector $v=[1,2,3]^\top$ and a plane in
$\mathbb{R}^3$, 

$$W = \{(x_1,x_2,x_3): x_1-x_2-x_3=0\},$$

We want to find the projection of $v$ onto $W$ using the following steps.



&#9989;  **<font color=red>QUESTION 2.1:</font>** (5 pts) In the markdown cell below, explain why $W$ forms a vector space and what the dimension of this space is.

As $W$ is in plane, $\mathbb{R}^3$, we need to prove that $W$ forms a vector space, we have to prove three condition:

1.) There exist a zero vector in $W$. Let us take any arbitary vector $x$ that is in $W$ and prove it.     

In [13]:
x = np.array([3,2,1])
zero = np.array([0,0,0])
print(x-zero)

[3 2 1]


Therefore, as you can see that zero vector, $x-z=x$.

2.) $W$ is closed, i.e., any vector $x,y \in W$, the $x+y \in W$.

In [14]:
x = np.array([3,2,1])
y = np.array([4,3,1])
xy = x + y
j = xy[0]
for i in range(1,len(xy)):
    j -= xy[i]
print(j)

0


As you can see that for $xy=x+y$, then $xy_1-xy_2-xy_3=0$.

3.) $W$ should be closed under scalar multiplication. This means that if $x\in W$, then for any scalar a $ax \in W$.

In [15]:
x = np.array([3,2,1])
y = 2
xy = y * x
j = xy[0]
for i in range(1,len(xy)):
    j -= xy[i]
print(j)

0


As you can see that for $xy=y.x$, then $xy_1-xy_2-xy_3=0$.

Therefore, as you can see that $W$ satisfies all the condition, it forms a vector space.

The dimension of $W$ is 2.

&#9989;  **<font color=red>QUESTION 2.2:</font>** (5 pts) Find a $1\times3$ matrix $A$ such that $W$ is the nullspace of $A$. 

In [16]:
#put your answer here
A = np.matrix([1,-1,-1])

In [17]:
from answercheck import checkanswer
checkanswer.matrix(A/np.sum(A),"78a91075ca3e5dca89273eaa2bda26d6");

Testing [[-1.  1.  1.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 2.3:</font>** (5 pts)
Find two arbitrary vectors in the plane $W$ that are not parallel with each other.

In [18]:
# Put your answer to the above question here
v1 = np.array([4,3,1])
v2 = np.array([3,1,2])

&#9989;  **<font color=red>QUESTION 2.4:</font>** (5 pts)
Orthogonalize `v1` and `v2` by applying the Gram-Schmidt process. Store the resulting orthonormal vectors as `w1` and `w2`

In [19]:
#Put your answer to the above question here
w1 = v1/np.linalg.norm(v1)
u2 = v2 - (np.dot(v2,w1)/np.dot(w1,w1))*w1
w2 = u2/np.linalg.norm(u2)
print(w1)
print(w2)

[0.78446454 0.58834841 0.19611614]
[ 0.22645541 -0.56613852  0.79259392]


&#9989;  **<font color=red>QUESTION 2.5:</font>** (5 pts) Use python to verify that {`w1`,`w2`} is indeed an orthonormal basis of the plane $W$. Specifically, verify

-  each basis vector has unit length 
-  orthogonality between different basis vectors.
-  `w1`, `w2` $\in W$ 

**1.) Lets check the length of the vector:**

In [20]:
#Put your answer to the above question here
print(round(np.linalg.norm(w1)))
print(round(np.linalg.norm(w2)))

1
1


**2.) Orthogonality between the basis vector should be that there dot product should be zero.**

In [21]:
print(round(np.dot(w1,w2)))
print(round(np.dot(w2,w1)))

0
0


**3.) For `w1`, `w2` $\in W$, the component of `w1` and `w2` should satisfy the condition $\{(x_1,x_2,x_3): x_1-x_2-x_3=0\}$**

In [22]:
def IsSatisfied(a):
    n = len(a)
    x = a[0]
    for i in range(1,n):
        x -= a[i]
    return round(x)

In [23]:
print(IsSatisfied(w1))
print(IsSatisfied(w2))

0
0


As you can see that `w1` and `w2` satisfies all the conditions. Therefore, {`w1`,`w2`} is indeed an orthonormal basis of the plane $W$.

Recall that in Pre-class 13, the following matimatical definition of projection onto a subspace is defined.

**Definition**: Let $W$ be a subspace of $R^n$ of dimension $m$. Let $\{w_1,\cdots,w_m\}$ be an orthonormal basis for $W$. Then the projection of vector $v$ in $R^n$ onto $W$ is denoted as $\mbox{proj}_Wv$ and is defined as 
$$\mbox{proj}_Wv = (v\cdot w_1)w_1+(v\cdot w_2)w_2+\cdots+(v\cdot w_m)w_m$$


&#9989;  **<font color=red>QUESTION 2.6:</font>** (5 pts) Use this formula to find $P_w v$, the projection of $v=[1,2,3]^T$ onto $W$


$$\mbox{proj}_u v = \frac{v \cdot u}{u \cdot u} u.$$

In [24]:
# Put your answer to the above question here
v = np.matrix([[1,2,3]])
Pwv = np.dot(v,w1)*w1 + np.dot(v,w2)*w2

In [25]:
from answercheck import checkanswer
checkanswer.vector(Pwv,"12feaf840c4568ff3b931d582147f6da");

Testing [[2.33333 0.66667 1.66667]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 2.7:</font>** (5 pts) What is the geometric meaning of $v-P_w v$? Use this to find the distance from $v$ to $W$.

In [26]:
#Put your code here
distance = np.linalg.norm(v-Pwv)

In [27]:
from answercheck import checkanswer
checkanswer.matrix(distance,"dd5b8b47bdfbbad36cedf5ee17fe60b1");


    Trying to convert to a array matrix using ```A = np.matrix(A)```.

Testing [[2.3094]]
Answer seems to be correct



# 3. Properties of orthogonal matrices (30 pts)


In pre-class 13, we learnt the definition of orthogonal matrices. Let us  review it here.

**Definition:** A $n\times n$ matrix $U$ is orthogonal if the columns of $U$ form an orthonormal basis of  $\mathbb {R} ^{n}$.

Orthogonal matrices have many alternative definitions. Explictly, the following conditions are all equivalent.

- $U$ is orthogonal

- the rows of $U$ form an orthonormal basis of  $\mathbb {R} ^{n}$.

- the columns of $U$ form an orthonormal basis of  $\mathbb {R} ^{n}$.

- Given two vectors x and y in $\mathbb{R}^n$, multiplication by U preserves their dot product; that is, $(Ux)\cdot (Uy) = x \cdot y$.
 
- U is invertible, and $U^T = U^{-1}$

&#9989;  **<font color=red>QUESTION 3.1:</font>** (5 pts) Let $v_1 = [\frac{1}{\sqrt 2}, 0, \frac{1}{\sqrt 2}]$, $v_2 = [0, 1, 0]$, $v_3 = [\frac{1}{\sqrt 2}, 0, -\frac{1}{\sqrt 2}]$.

Use a subset of the above equivalent conditions to verify that $v_1,v_2,v_3$ form an orthonormal basis of $\mathbb{R}^3$.

In [28]:
#put your code here
v1 = np.array([(1/np.sqrt(2)),0,(1/np.sqrt(2))])
v2 = np.array([0,1,0])
v3 = np.array([(1/np.sqrt(2)),0,-(1/np.sqrt(2))])
print(np.dot(v1,v2))
print(np.dot(v1,v3))
print(np.dot(v2,v3))

0.0
0.0
0.0


As you can see that the dot product of all the vector are zero, then it forms an orthonormal basis of $\mathbb{R}^3$. 

In [29]:
U = np.matrix([[(1/np.sqrt(2)),0,(1/np.sqrt(2))],[0,1,0],[(1/np.sqrt(2)),0,-(1/np.sqrt(2))]])
sym.Matrix(U.T)

⎡0.707106781186547  0.0  0.707106781186547 ⎤
⎢                                          ⎥
⎢       0.0         1.0         0.0        ⎥
⎢                                          ⎥
⎣0.707106781186547  0.0  -0.707106781186547⎦

In [30]:
U_inv = np.linalg.inv(U)
sym.Matrix(U_inv)

⎡0.707106781186548  0.0  0.707106781186548 ⎤
⎢                                          ⎥
⎢       0.0         1.0         0.0        ⎥
⎢                                          ⎥
⎣0.707106781186548  0.0  -0.707106781186548⎦

 U is invertible, and $U^T = U^{-1}$

In [31]:
print(round(np.linalg.det(U)))

-1


Therefore, `U` is orthonormal and $v_1,v_2,v_3$ forms the orthonormal basis of $\mathbb{R}^3$ because $U^T = U^{-1}$ and the determinant of $det(U) = 1$

&#9989;  **<font color=red>QUESTION 3.2:</font>** (5 pts) Use python code  to construct the following two $3\times 3$ transformation matrices: 
+ Rotation matrix `R` that rotates a given vector in $\mathbb{R}^3$ around the $x$-axis clockwise by an angle of $70^\circ$ 
+ Reflection matrix `F` that rotates a given vector in $\mathbb{R}^3$ about the $x$-$y$ plane.

In [32]:
#put your code here
degrees = 70
x = degrees/180 * np.pi
cos_x = np.cos(x)
sin_x = np.sin(x)
R = np.matrix([[1,0,0],[0,cos_x,-sin_x],[0,sin_x,cos_x]])
F = np.matrix([[1,0,0],[0,1,0],[0,0,-1]])
print("Matrix F : ")
sym.Matrix(F)

Matrix F : 


⎡1  0  0 ⎤
⎢        ⎥
⎢0  1  0 ⎥
⎢        ⎥
⎣0  0  -1⎦

In [33]:
print("Matrix R : ")
sym.Matrix(R)

Matrix R : 


⎡1.0         0.0                0.0        ⎤
⎢                                          ⎥
⎢0.0  0.342020143325669  -0.939692620785908⎥
⎢                                          ⎥
⎣0.0  0.939692620785908  0.342020143325669 ⎦

&#9989;  **<font color=red>QUESTION 3.3:</font>** (5 pts) Verify that `R`,`F` and their products `RF`, `FRFR` are all orthogonal. This tells us that any combination of orthogonal matrices is still orthogonal.

**To prove that `R` is an orthonormal matrix**

In [34]:
#put your code here
R_transpose = np.matrix(R).T
R_inv = np.linalg.inv(R)
#sym.Matrix(R_inv)
print(np.allclose(R_transpose, R_inv))
print(round(np.linalg.det(R)))

True
1


`R` is orthonormal because $R^T = R^{-1}$ and the determinant of $det(R) = 1$

**To prove that `F` is an orthonormal matrix**

In [35]:
F_transpose = np.matrix(F).T
F_inv = np.linalg.inv(F)
#sym.Matrix(R_inv)
print(np.allclose(F_transpose, F_inv))
print(round(np.linalg.det(F)))

True
-1


`F` is orthonormal because $F^T = F^{-1}$ and the determinant of $det(F) = -1$

**To prove that `RF` is an orthonormal matrix**

In [36]:
RF = R*F
RF_transpose = np.matrix(RF).T
RF_inv = np.linalg.inv(RF)
print(np.allclose(RF_transpose, RF_inv))
print(round(np.linalg.det(RF)))

True
-1


`RF` is orthonormal because ${RF}^T = {RF}^{-1}$ and the determinant of $det(RF) = -1$

**To prove that `FRFR` is an orthonormal matrix**

In [37]:
FRFR = F*R*F*R
FRFR_transpose = np.matrix(FRFR).T
FRFR_inv = np.linalg.inv(FRFR)
print(np.allclose(FRFR_transpose, FRFR_inv))
print(round(np.linalg.det(FRFR)))

True
1


`FRFR` is orthonormal because ${FRFR}^T = {FRFR}^{-1}$ and the determinant of $det(FRFR) = -1$

&#9989;  **<font color=red>QUESTION 3.4:</font>** (5 pts) Rotations and reflections are known as rigid motions, meaning that they do not change the length of the vectors being rotated/reflected. This is in fact an intrinsic property of orthogonal matrices and is guaranteed by one of the equivalent conditions of orthogonal matrices listed above. Which condition is that? Provide your explanation. 

(Hint: for an orthogonal matrix $U$, when we say it does not change the length of the input, we mean $\|Ux\|=\|x\|$ for any $x$, that is, the length of $Ux$ is always the same as the length of $x$. You are asked to find the condition of orthogonal matrices that implies this.)

Using the condition:

Given two vectors x and y in $\mathbb{R}^n$, multiplication by U preserves their dot product; that is, $(Ux)\cdot (Uy) = x \cdot y$.

Since, this is true for any given vector $x$ and $y$, we can substitude $y$ with $x$.

It gives us $(Ux)\cdot (Ux) = x \cdot x$.

We know that the dot problem of a vector or matrix is equal to its norm or its length and therefore, we know that $\|Ux\|=\|x\|$ is same as  $(Ux)\cdot (Ux) = x \cdot x$. This means that using the condition just stated, we have orthogonal matrices have rigid motions.

&#9989;  **<font color=red>QUESTION 3.5:</font>** (5 pts) Find the value $a-f$ such that
$$A = \begin{bmatrix}
1 & a & b \\
c & 0.6 & d \\
e & 0.8 & f
\end{bmatrix}$$
is orthogonal.

In [137]:
a=0
b=0
c=0
d=-0.8
e=0
f=0.6
A = np.matrix([[1,0,0],[0,0.6,-0.8],[0,0.8,0.6]])

In [138]:
from answercheck import checkanswer
checkanswer.vector([a,b,c,abs(d),e,f*d], "1592b4d30e72d792d5e5c17c5eb1c4a6");


    Trying to convert to a array matrix using ```A = np.matrix(A)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[ 0.    0.    0.    0.8   0.   -0.48]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 3.6:</font>** (5 pts) Compute the eigenvalues of all the orthogonal matrices mentioned in QUESTION 3.4 and QUESTION 3.5, what did you find about the magnitudes of these eigenvalues? Could you come up with a theoretical explanation for this phenomenon?

In [139]:
#Put your code here
print("Magnitude for R: ")
print(round(abs(np.linalg.eig(R)[0][0])), round(abs(np.linalg.eig(R)[0][1])),round(abs(np.linalg.eig(R)[0][2])))
print()
print("Magnitude for F: ")
print(round(abs(np.linalg.eig(F)[0][0])), round(abs(np.linalg.eig(F)[0][1])),round(abs(np.linalg.eig(F)[0][2])))
print()
print("Magnitude for RF: ")
print(round(abs(np.linalg.eig(RF)[0][0])), round(abs(np.linalg.eig(RF)[0][1])),round(abs(np.linalg.eig(RF)[0][2])))
print()
print("Magnitude for FRFR: ")
print(round(abs(np.linalg.eig(FRFR)[0][0])), round(abs(np.linalg.eig(FRFR)[0][1])),round(abs(np.linalg.eig(FRFR)[0][2])))
print()
print("Magnitude for A: ")
print(round(abs(np.linalg.eig(A)[0][0])), round(abs(np.linalg.eig(A)[0][1])),round(abs(np.linalg.eig(A)[0][2])))

Magnitude for R: 
1 1 1

Magnitude for F: 
1 1 1

Magnitude for RF: 
1 1 1

Magnitude for FRFR: 
1 1 1

Magnitude for A: 
1 1 1


**As our rotation and reflection are rigid, they are not streching and our eigenvalues tell us about the strech of a eigenvectors. Having absolute eigenvalue value magnitude is equal to 1, it means that it is not stretched and we have the rigid rotation and reflection.**

### Congratulations, we're done!