In order to successfully complete this assignment we recommend that you participate both individually and in groups during class. **Turn in your assignment using D2L no later than 11:59pm on the day of class.** Grading is based on correctness and completion.


# 15 In-Class Assignment: Diagonalization

<img alt="Classig equation for diagonalizing a matrix. Will be discussed in class" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/62ab0ef52ecb1e1452efe6acf096923035c75f62" width="50%">

Image from: [https://en.wikipedia.org/wiki/Diagonalizable_matrix](https://en.wikipedia.org/wiki/Diagonalizable_matrix)

    

### Agenda for today's class (80 minutes)

1. [(30 minutes) Pre-class Assignment Review](#Pre-class_Assignment_Review)
1. [(35 minutes) Diagonalization](#Diagonalization)
1. [(15 minutes) The Power of a Matrix](#The_Power_of_a_Matrix)


In [1]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing()

---
<a name="Pre-class_Assignment_Review"></a>
## 1. Pre-class Assignment Review

----
<a name="Diagonalization"></a>
## 2. Diagonalization

**_Reminder_**: The eigenvalues of triangular (upper and lower) and diagonal matrices are easy:

* The eigenvalues for triangular matrices are the diagonal elements.
* The eigenvalues for the diagonal matrices are the diagonal elements. 

### Diagonalization


**Definition**: A square matrix $A$ is said to be *diagonalizable* if there exist a matrix $C$ such that $D=C^{-1}AC$ is a diagonal matrix.

**Definition**: $B$ is a *similar matrix* of $A$ if we can find $C$ such that $B=C^{-1}AC$.


Given an $n\times n$ matrix $A$, can we find another $n \times n$ invertable matrix $C$ such that when $D=C^{-1}AC$ is diagonal, i.e., $A$ is diagonalizable?

* Because $C$ is inveritble, we have 
$$C^{-1}AC=D \\ CC^{-1}AC = CD\\ AC = CD $$


* Generate $C$ as the columns of $n$ linearly independent vectors $(x_1...x_n)$. We can compute $AC=CD$ as follows:
$$ A\begin{bmatrix} \vdots  & \vdots  & \vdots  & \vdots  \\ \vdots  & \vdots  & \vdots  & \vdots  \\ { x }_{ 1 } & { x }_{ 2 } & \dots  & { x }_{ n } \\ \vdots  & \vdots  & \vdots  & \vdots  \end{bmatrix}=AC=CD=\begin{bmatrix} \vdots  & \vdots  & \vdots  & \vdots  \\ \vdots  & \vdots  & \vdots  & \vdots  \\ { x }_{ 1 } & { x }_{ 2 } & \dots  & { x }_{ n } \\ \vdots  & \vdots  & \vdots  & \vdots  \end{bmatrix}\begin{bmatrix} { \lambda  }_{ 1 } & 0 & 0 & 0 \\ 0 & { \lambda  }_{ 2 } & 0 & 0 \\ \vdots  & \vdots  & { \dots  } & \vdots  \\ 0 & 0 & 0 & { \lambda  }_{ n } \end{bmatrix}$$
* Then we check the corresponding columns of the both sides. We have 
$$Ax_1 = \lambda_1x_1\\\vdots\\Ax_n=\lambda x_n$$

* $A$ has $n$ linear independent eigenvectors.

* $A$ is said to be *similar* to the diagonal matrix $D$, and the transformation of $A$ into $D$ is called a *similarity transformation*.

### A simple example

Consider the following:
$$ A = \begin{bmatrix}7& -10\\3& -4\end{bmatrix},\quad C = \begin{bmatrix}2& 5\\1& 3\end{bmatrix}$$

&#9989;  **<font color=red>Do this:</font>** Find the similar matrix $D = C^{-1}AC$ of $A$.

In [2]:
#Put your answer to the above question here.
A = np.matrix([[7,-10],[3,-4]])
eigval, eigvec = np.linalg.eig(A)
#D = np.matrix([[eigval[0],0],[0,eigval[1]]])
C = eigvec
C_inv = np.linalg.inv(C)
D = C_inv*A*C

In [3]:
from answercheck import checkanswer

checkanswer.matrix(D, '8313fe0f529090d6a8cdb36248cfdd6c');


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[2. 0.]
 [0. 1.]]
Answer seems to be correct



&#9989;  **<font color=red>Do this:</font>** Find the eigenvalues and eigenvectors of $A$. Set variables ```e1``` and ```vec1``` to be the smallest eigenvalue and its associated eigenvector and ```e2, vec2``` to represent the  largest.

In [4]:
#Put your answer to the above question here.
print(eigval)
print(eigvec)
e1 = 1
e2 = 2
vec2 = eigvec[:,0]
vec1 = eigvec[:,1]
print(vec1)

[2. 1.]
[[0.89442719 0.85749293]
 [0.4472136  0.51449576]]
[[0.85749293]
 [0.51449576]]


In [5]:
from answercheck import checkanswer
checkanswer.float(e1, "e4c2e8edac362acab7123654b9e73432");


    Trying to convert to a float using ```A = float(A)```.

Testing 1.0
Answer seems to be correct



In [6]:
from answercheck import checkanswer
checkanswer.float(e2, "d1bd83a33f1a841ab7fda32449746cc4");


    Trying to convert to a float using ```A = float(A)```.

Testing 2.0
Answer seems to be correct



In [7]:
from answercheck import checkanswer
checkanswer.eq_vector(vec1, "d28f0a721eedb3d5a4c714744883932e", decimal_accuracy = 4)


    Trying to convert to a column vector using ```A = A.T```.


    Trying to normalize to unit vector to check answer using
    using ```A = A/1.000008249965969```.


Testing [[0.8575 0.5145]]
Answer seems to be correct



In [8]:
from answercheck import checkanswer
checkanswer.eq_vector(vec2, "09d9df5806bc8ef975074779da1f1023", decimal_accuracy = 4)


    Trying to convert to a column vector using ```A = A.T```.


    Trying to normalize to unit vector to check answer using
    using ```A = A/0.999969599537906```.


Testing [[0.8944 0.4472]]
Answer seems to be correct



**Theorem:** Similar matrices have the same eigenvalues.

**Proof:** Assume $B=C^{-1}AC$ is a similar matrix of $A$, and $\lambda$ is an eigenvalue of $A$ with corresponding eigenvector $x$. That is, $$Ax=\lambda x$$ 
Then we have $$B(C^{-1}x) = C^{-1}AC(C^{-1}x) = C^{-1}Ax = C^{-1}(\lambda x)= \lambda (C^{-1}x).$$
That is $C^{-1}x$ is an eigenvector of $B$ with eigenvalue $\lambda$.     

### A second example

&#9989;  **<font color=red>Do this:</font>** Consider 
$$ A = \begin{bmatrix}-4& -6\\3& 5\end{bmatrix}.$$
Find a matrix $C$ such that $C^{-1}AC$ is diagonal. (Hint, use the function `diagonalize` in `sympy`.)

In [9]:
#Put your answer to the above question here. 
A = sym.Matrix([[-4,-6],[3,5]])
C = A.diagonalize()
C = C[0]
C

⎡-2  -1⎤
⎢      ⎥
⎣1   1 ⎦

In [10]:
#Check the output type
assert(type(C)==sym.Matrix)

In [11]:
from answercheck import checkanswer
checkanswer.matrix(C,'ba963b7fef354b4a7ddd880ca4bac071')


    Trying to convert to a array matrix using ```A = np.matrix(A)```.


    Trying to convert to float using ```A = A.astype(float)```.

Testing [[-2. -1.]
 [ 1.  1.]]
Answer seems to be correct



### The third example

&#9989;  **<font color=red>Do this:</font>** Consider 
$$ A = \begin{bmatrix}5& -3\\3& -1\end{bmatrix}.$$
Can we find a matrix $C$ such that $C^{-1}AC$ is diagonal?  (Hint: find eigenvalues and eigenvectors using `sympy`)

In [12]:
#Put your answer to the above question here. 
A = np.matrix([[5,-3],[3,-1]])
eigval, eigvec = np.linalg.eig(A)
D = np.matrix([[eigval[0],0],[0,eigval[0]]])
C = eigvec
C_inv = np.linalg.inv(C)
D1 = C_inv*A*C
print(D1)

[[ 2.0000000e+00-2.98023224e-08j -8.8817842e-16-2.98023224e-08j]
 [-8.8817842e-16+2.98023224e-08j  2.0000000e+00+0.00000000e+00j]]


In [13]:
print(D)

[[2.+2.58095683e-08j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 2.+2.58095683e-08j]]


In [14]:
np.allclose(D1,D)

False

We cannot find the C matrix for A

### Dimensions of eigenspaces and diagonalization

**Definition**: The set of all eigenvectors of an $n\times n$ matrix corresponding to an eigenvalue $\lambda$, together with the zero vector, is a subspace of $\mathbb R^n$. This subspace is called the *eigenspace*.

* For the third example, we have that the characteristic equation $(\lambda-2)^2=0$.
* Eigenvalue $\lambda=2$ has multiplicity 2, but the eigenspace has dimension 1, since we can not find two linearly independent eigenvectors for $\lambda =2$. 

> The dimension of an eigenspace of a matrix is less than or equal to the multiplicity of the corresponding eigenvalue as a root of the characteristic equation.

> A matrix is diagonalizable if and only if the dimension of every eigenspace is equal to the multiplicity of the corresponding eigenvalue as a root of the characteristic equation.

### The fourth example

&#9989;  **<font color=red>Do this:</font>** Consider 
$$ A = \begin{bmatrix}2& -1\\1& 2\end{bmatrix}.$$
Can we find a matrix $C$ such that $C^{-1}AC$ is diagonal?

In [15]:
#Put your answer to the above question here. 
A = np.matrix([[2,-1],[1,2]])
C = np.linalg.eig(A)[1]
print(np.linalg.eig(A)[0])
sym.Matrix(C)

[2.+1.j 2.-1.j]


⎡ 0.707106781186547     0.707106781186547 ⎤
⎢                                         ⎥
⎣-0.707106781186547⋅ⅈ  0.707106781186547⋅ⅈ⎦

Yes, we can find the matrix C.

---

<a name="The_Power_of_a_Matrix"></a>
## 3. The Power of a Matrix

* For a diagonalizable matrix $A$, we have $C^{-1}AC=D$. Then we have 
$$A = C D C^{-1}$$
* We have 
$$A^2 = C D C^{-1} C D C^{-1} = C D^2 C^{-1}$$
$$A^n = C D C^{-1} \dots C D C^{-1} = C D^n C^{-1}$$
* The equality $A^n=C D^n C^{-1}$ holds for all integers $n$ (both positive and negative).
* Because the columns of $C$ are eigenvectors, so we can say that the eigenvectors for $A$ and $A^n$ are the same if $A$ is diagonalizable. 
* If $x$ is an eigenvector of $A$ with the corresponding eigenvalue $\lambda$, then $x$ is also an eigenvector of $A^n$ with the corresponding eigenvalue $\lambda^n$.

In [16]:
# Here are some libraries you may need to use
%matplotlib inline
import numpy as np
import sympy as sym
import networkx as nx
import matplotlib.pyplot as plt
sym.init_printing(use_unicode=True)

&#9989;  **<font color=red>Do this:</font>** Consider the matrix 
$$ A = \begin{bmatrix}-4& -6\\3& 5\end{bmatrix}$$ from the second example. Calculate $A^{-3}$ and $A^{10}$ in two different ways:
 * Directly, using `A**n` in Python for the appropriate values of n.

In [17]:
#Put your answer to the above question here. 
A = np.matrix([[-4,-6],[3,5]])
A_three = A**(-3)
A_ten = A**(10)
print(A_three)
print()
print(A_ten)

[[-2.125 -2.25 ]
 [ 1.125  1.25 ]]

[[-1022 -2046]
 [ 1023  2047]]


* By using the matrices $C$ and $D$ (you found them in the worksheet above), which diagonalize $A$.

In [18]:
#Put your answer to the above question here. 
eigval, eigvec = np.linalg.eig(A)
C = eigvec
D = np.matrix([[eigval[0],0],[0,eigval[1]]])
C_inv = np.linalg.inv(C)
A_three = C*(D**(-3))*C_inv
A_ten = C*(D**(10))*C_inv
print(A_three)
print()
print(A_ten)

[[-2.125 -2.25 ]
 [ 1.125  1.25 ]]

[[-1022. -2046.]
 [ 1023.  2047.]]


 * Compare the two approaches. Discuss which approach you'd rather take if you were doing things by hand and why.

By  hand, the second approach is better, because it is much easier.

----
Written by Dr. Dirk Colbry, Michigan State University
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.


-----
### Congratulations, we're done!
