In order to successfully complete this assignment you must do the required reading, watch the provided videos and complete all instructions.  The pre-class assignment quiz must be submitted on D2L on or before **_11:59pm on on the day before class_**.  Students must come to class the next day prepared to discuss the material covered in this assignment.

# 15 Pre-Class Assignment: Diagonalization and Powers

### Readings for this topic (Recommended in bold)
 * [Heffron Chapter 5 II1-2 pg 388-396](http://joshua.smcvt.edu/linearalgebra/book.pdf)
 * [**_Beezer Section SD pg 403-415_**](http://linear.ups.edu/download/fcla-3.50-tablet.pdf)


### Goals for today's pre-class assignment 

1. [Eigenvalues and eigenvectors review](#Eigenvalues_and_eigenvectors_review)
1. [Diagonalizable Matrix](#Diagonalizable_Matrix)

----
<a name="Eigenvalues_and_eigenvectors_review"></a>
## 1. Eigenvalues and eigenvectors review

**Definition**: A non-zero vector $x$ in $\mathbb R^n$ is called an *eigenvector* of an $n\times n$ matrix $A$ if $Ax$ is a scalar multiple of $x$ (i.e. $Ax$ has the same direction as $x$). If $Ax = \lambda x$, then $\lambda$ is called the *eigenvalue* of $A$ corresponding to $x$.

### Steps for finding the eigenvalues and eigenvectors

We want to find $\lambda$ and a non-zero vector $x$ such that $Ax=\lambda x$ for an $n\times n$ matrix. 
1. We introduce an identity matrix $I$ of size $n\times n$. Then the equation becomes
$$Ax = \lambda I x$$
$$Ax-\lambda I x = 0$$
$$(A-\lambda I)x = 0$$
2. This suggests that we want to find $\lambda$ such that $(A-\lambda I)x=0$ has a non-trivial solution. 
It is equivalent to the matrix $A-\lambda I$ being singular, i.e., it having a determinant of $0$.
$$|A-\lambda I|=0$$
3. The determinant is a polynomial in $\lambda$ (called the characteristic polynomial of $A$) with degree $n$. We solve this equation (called the characteristic equation) for all possible $\lambda$ (eigenvalues).
4. After finding the eigenvalues, we substitute them back into 
$$(A-\lambda I)x=0$$
and find the eigenvectors $x$. 


Let's calculate eigenvalues for the following matrix: 

$$ A=\begin{bmatrix} 0 & 0 & -2 \\ 1 & 2 & 1 \\ 1 & 0 & 3 \end{bmatrix}$$

#### Find eigenvalues
Looking at the above recipe, let's solve the problem symbollically using `sympy`. First let's create a matrix $B$ such that:

$$B = A-\lambda I$$

In [1]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing()

In [2]:
#Most sympy requires defeing the variables as "symbols"
#Once we do this we can use the variables in place of numbers
lam = sym.symbols('lambda')

A = sym.Matrix([[0, 0 ,-2], [1, 2, 1], [1, 0, 3]])
I = sym.eye(3)

B = A - lam*I

B

⎡-λ    0     -2  ⎤
⎢                ⎥
⎢1   2 - λ    1  ⎥
⎢                ⎥
⎣1     0    3 - λ⎦

Now, per step 2, the determinant of $B$ must be zero. Note that `sympy` calculates the determinate symbollically as follows:

In [3]:
B.det()

&#9989; **<font color=red>Do This:</font>**  Using the ```sympy.solve``` function on the determinate of $B$ to solve for ```lam``` ($\lambda$). Verify that the solution to the last question produces the same eigenvalues as above. 

In [4]:
# Put your code to solve for det(B) = 0 her
x = sym.solve((B.det(),0))
x

&#9989; **<font color=red>Do This:</font>**  First, let's use the built in function ```eigenvals``` function in ```sympy``` to calculate the eigenvalues. Find out the meaning of the output.

In [5]:
# Put your code here
B.eigenvals()

In [6]:
B.eigenvects()

⎡⎛          ⎡⎡-2⎤⎤⎞  ⎛          ⎡⎡0⎤  ⎡-1⎤⎤⎞⎤
⎢⎜          ⎢⎢  ⎥⎥⎟  ⎜          ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎢⎜1 - λ, 1, ⎢⎢1 ⎥⎥⎟, ⎜2 - λ, 2, ⎢⎢1⎥, ⎢0 ⎥⎥⎟⎥
⎢⎜          ⎢⎢  ⎥⎥⎟  ⎜          ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎣⎝          ⎣⎣1 ⎦⎦⎠  ⎝          ⎣⎣0⎦  ⎣1 ⎦⎦⎠⎦

**Explain your output here.**

#### Find eigenvectors
Now we know the eigenvalues, we can substitue them back into the equation to find the eigenvectors.  
We solve this symbollically using `sympy`. First let's make a vector of our eigenvalues (from above):

In [7]:
eig = [1,2]

Now (per step 4 above) we need to solve the equation $(A-\lambda I)x=0$. One way to do this in `sympy` is as follows:

In [8]:
x1,x2,x3 = sym.symbols(['x_1','x_2','x_3'])

x = sym.Matrix([[x1],[x2],[x3]])
x

⎡x₁⎤
⎢  ⎥
⎢x₂⎥
⎢  ⎥
⎣x₃⎦

In [9]:
for lam in eig:
    vec = sym.solve((A - lam*I)*x,x)
    print(vec)

{x_1: -2*x_3, x_2: x_3}
{x_1: -x_3}


&#9989; **<font color=red>QUESTION:</font>**  Explain your output here. (Hint, you can also try the `rref` to find the solutions)

**Put your answer here.**

&#9989; **<font color=red>Do This:</font>**  Next, let's use the ```eigenvects```  function in ```sympy``` to find three linear independent eigenvectors for the matrix $A$?

In [10]:
# Put your answer to the above question here

&#9989; **<font color=red>QUESTION:</font>**  Compare this answer to the eigenvectors we calculated above. Does this answer make sense?  What does the syntax tell us? 

**Put your answer here.**

&#9989; **<font color=red>DO THIS:</font>** Find the eigenvalues and eigenvectors of the following matrix:
$$ A2=\begin{bmatrix} 2 & 1 \\ 0 & 2 \end{bmatrix}$$

In [11]:
# Put your code here

&#9989; **<font color=red>QUESTION:</font>**  What are the eigenvalues for the matrix $A2$?

**Put your answer to the above question here.**

&#9989; **<font color=red>QUESTION:</font>**  What are the eigenvectors for the matrix $A2$?

**Put your answer to the above question here.**

----
<a name="Diagonalizable_Matrix"></a>
## 2. Diagonalizable Matrix

In class we will be using matrix diagonalization to solve some problems.  

**Definition**: If $A$ and $B$ are $n\times n$ (square) matrices, then $A$ is said to be
**similar** to $B$ if there exists an invertible matrix, $P$, such that $A =
P^{-1}BP$.

One can use the fact that $\mbox{det}(A)=\mbox{det}(P^{-1}BP)= \mbox{det}(P^{-1})\mbox{det}(B)\mbox{det}(P)$ to prove the following theorem.

**Theorem:** If the matrices $A$ and $B$ are similar to each other, then $A$ and $B$
have the same characteristic equation, and hence have the same eigenvalues.

**Definition:** The matrix $A$ is diagonalizable if there exists a diagonal matrix $D$ that is similar similar to $A$:

$$ D = C^{-1}AC$$

If the matrix $A$ has linearly independent eigenvectors ($v_1, \ldots v_n$) then $A$ is diagonalizable with the following solution:

$$C = \left[ v_1^T, \ldots, v_n^T \right]$$

In other words, each column of $C$ is a linearly independent eigenvector of $A$. The diagonal matrix $D$ is

$$ D = 
\left[
\begin{matrix}
    \lambda_1  & 0  & 0 \\
    0   & \ddots & 0  \\
    0   & 0 & \lambda_n 
\end{matrix}
\right] 
$$

In other-other words, $D$ consists of the corresponding eigenvalues.

In [12]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

&#9989; **<font color=red>DO THIS:</font>** Using ```numpy```, Diagonalize (i.e. calculate  C and D) the following matrix:

In [13]:
A = np.matrix([[5, -2, 2], [4, -3, 4], [4,-6,7]])
sym.Matrix(A)

⎡5  -2  2⎤
⎢        ⎥
⎢4  -3  4⎥
⎢        ⎥
⎣4  -6  7⎦

In [15]:
# Put your answer here
print(np.linalg.eig(A))
D = np.matrix([[5,0,0],[0,1,0],[0,0,3]])

(array([5., 1., 3.]), matrix([[-5.77350269e-01,  6.40987562e-17, -7.07106781e-01],
        [-5.77350269e-01,  7.07106781e-01,  1.11022302e-16],
        [-5.77350269e-01,  7.07106781e-01,  7.07106781e-01]]))


In [16]:
from answercheck import checkanswer

checkanswer.matrix(D,'56821475223b52e0b6e751da444a1441');


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[5. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]
Answer seems to be correct



&#9989; **<font color=red>DO THIS:</font>** Verify that $A$ is in fact Diagonalizable by calculating $D2 = C^{-1}AC$ and comparing it to your original $D$ using ```np.allclose```.

In [17]:
#Put your verificaiton code here.
eigval, eigvec = np.linalg.eig(A)
C = eigvec
C_inv = np.linalg.inv(C)
D2 = C_inv*A*C
print(D2)

[[ 5.00000000e+00  8.88178420e-16 -1.77635684e-15]
 [-8.88178420e-16  1.00000000e+00 -2.66453526e-15]
 [ 8.88178420e-16 -8.88178420e-16  3.00000000e+00]]


In [18]:
np.allclose(D,D2)

True

### Diagonalization of Symmetric Matrices

One special case is Symmetric Matrices. 

**Definition:** A matrix is called a **symmetric** matrix if its transpose is equal to the matrix itself, i.e. $A = A^T$.
If $a_{ij}$ denotes the entry in an i-th row and j-th column, then the symmetric matrix satisfies $a_{ij} = a_{ji}$.For example, the following is a $3\times 3$ symmetric matrix:
$A=\left[\matrix{1& 2 & 7 \\ 2 & 4&  5 \\ 7 & 5 & 9}\right]$.

**Definition:** A matrix, $A$, is called **orthogonal** if its columns form a set of orthonormal vectors. One can show that the following statements are equivalent:

* the columns of $A$ form a set of orthonormal vectors;
* the rows of $A$ form a set of orthonormal vectors;
* $A^TA=I$.

It can be shown that symmetric matrices are diagonalizable and the resulting eigenvectors are not only linearly independent but also orthogonal. Since this is true, the equation changes to: 


$$ D = C^{T}AC$$

&#9989; **<font color=red>QUESTION:</font>** Why do we care if $C$ is orthogonal?  What advantages does the above equation give us?

**Put your answer to the above question here.**

### Congratulations, we're done!

Written by Dr. Dirk Colbry, Michigan State University
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

----